### ISSUE TITLE
Doesn't restore the original rules

### ISSUE THREAD

**Issue by NKjoep** [eamodio/vscode-toggle-excluded-files#1]
For instance, with this `files.exclude` settings:

```json
{
  "files.exclude": {
     "**/*.js": {"when": "$(basename).ts"}
  }
}
```

Then using your toggler it restores the config overriding the original rule config with `true|false`, like this:

```json
{
  "files.exclude": {
     "**/*.js": true
  }
}
```

Do you think is it possible to improve this? :)

**Comment by eamodio** [comment]
@NKjoep Thanks for the report -- I will definitely look into fixing this. (Honestly I didn't even know you could do that in an exclude!) :)

**Comment by NKjoep** [comment]
Yep it is possible and it is super handy!

If you [read this doc](https://code.visualstudio.com/updates/v0_5_0#_editor-options) they explain how to use the patterns.

AFAIK, supported keywords are `$(basename)` and `$(filename)`, there's also an open issue about that https://github.com/Microsoft/vscode/issues/4642
