### ISSUE TITLE
Wrong settings.json handling

### ISSUE THREAD

**Issue by myfairsyer** [eamodio/vscode-toggle-excluded-files#10]
`vscode-toggle-excluded-files` doesn't handle vscode's user setting correctly.
1. It directly parses settings.json instead of [accessing settings via configuration API in vscode.d.ts](https://github.com/Microsoft/vscode/issues/26830#issuecomment-322213682)
1. It parses them as regular JSON although vscode settings files are "[JSONC](https://github.com/Microsoft/vscode/commit/0c2de000436cd9eb1d6ea07b1cbcd61cc4acf9f8)" and allow comments and trailing commas ([MS's jsonc parser](https://github.com/Microsoft/node-jsonc-parser))
1. Trailing commas and comments cause an exception being thrown
1. The exception is not being caught/handled
1. This makes the extension break/crash.

**Comment by myfairsyer** [comment]
These might (or might not) be helpful hints/links:
- https://code.visualstudio.com/api/references/vscode-api#workspace.getConfiguration
- https://github.com/Microsoft/vscode-extension-samples/tree/master/configuration-sample

**Comment by eamodio** [comment]
@myfairsyer I'm not sure what code you are looking at but this extension DOES use the vscode configuration apis and doesn't parse any JSON directly.

What are the actual issues you are seeing?

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Comment by myfairsyer** [comment]
Sorry for not responding earlier.

IIRC I installed another similar extension alongside `vscode-toggle-excluded-files` which actually showed the behavior observed.

I just mixed them up and filed the issue in the wrong repo (and using the "wrong" name)
