### ISSUE TITLE
Doesn't turn off

### ISSUE THREAD

**Issue by rhys-vdw** [eamodio/vscode-toggle-excluded-files#2]
So I can reveal all the files, but then I can't hide them again. The icon remains in this state:

![image](https://cloud.githubusercontent.com/assets/822105/23775314/34b651fe-057c-11e7-9deb-010d4f96bfdf.png)

And I can just see all my files. Even when I quit and reopen VSCode.

It did work the first few times I tried toggling it (albeit incredibly slowly). Now it seems to have completely stopped working (regardless of whether I use the keyboard shortcut, click the button or select it from the cmd+shift+p menu).

**Comment by rhys-vdw** [comment]
(I see the icon doesn't reflect the toggle state - nonetheless it isn't re-hiding my excluded files)

**Comment by eamodio** [comment]
@rhys-vdw can you set both `"toggleexcludedfiles.advanced.debug": true` and `"toggleexcludedfiles.advanced.output.level": "verbose"`, and then see if you can reproduce the problem. If so, there should be a log in the `ToggleExcludedFiles` output channel. Hopefully it will reveal something.

Also can you post what your `files.exclude` setting is set to?

**Comment by rhys-vdw** [comment]
@eamodio I disabled the plugin when it was playing up. After re-enabling the issue has gone away. I will keep an eye out to see if it happens again and follow your instructions then. Sorry to not be more useful!

**Comment by eamodio** [comment]
@rhys-vdw no worries at all -- let me know if it comes back, but I'm going to close this until then.
