### ISSUE TITLE
"toggleexcludedfiles.statusBar.enabled" is only considered when restarting VSCode

### ISSUE THREAD

**Issue by charles-allen** [eamodio/vscode-toggle-excluded-files#24]
**Expected**:
- Changing `toggleexcludedfiles.statusBar.enabled` would immediately update the status bar

**Actual:**
- Nothing happens (initially)
- Setting is respected if I restart VSCode

**Reproduction steps:**
- Install extension
- Open Settings (UI)
- Uncheck "Toggleexcludedfiles > Status Bar: Enabled"

**Context:**
- Extension version: 1.7.0
- VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
- OS: MacOS Darwin x64 19.6.0

**Comment by eamodio** [comment]
I believe this issue has been resolved in the latest version.
