### ISSUE TITLE
settings.json content gets pasted into open file on toggle

### ISSUE THREAD

**Issue by yadejo** [eamodio/vscode-toggle-excluded-files#3]
When I click on the toggle icon in the statusbar, while a file is opened, the content of settings.json gets pasted into this file. 

![image](https://cloud.githubusercontent.com/assets/5558600/26248440/b8fae27e-3ca2-11e7-810a-2bacfe39e85a.png)

**Comment by eamodio** [comment]
@yadejo Um wow that's an odd one 😄 

This extension doesn't touch any files -- it uses the vscode api directly to manipulate the vscode settings, so I am at a complete loss as to how this would even be possible. What version of vscode are you running? Do you have any other extensions installed -- something specifically for `.gitignore` or something? I would recommend trying to disable all your other extensions (temporarily) and see if the problem still persists.

**Comment by yadejo** [comment]
I'll have to check on monday at work. Can't seem to reproduce it on my personal laptop.

**Comment by yadejo** [comment]
It's fixed. It wasn't a bug in vscode-toggle-excluded-files, but in JS-CSS-HTML formatter extension. This extension, for some reason, assumes that the file being saved, is always the file that is currently open in the editor and replaces the content of the open file with the formatted version of the saved file.

vscode-toggle-excluded-files automaticly changes settings.json, and saves it. The other extension formats this file and replaces the content of the currently open file with the formatted content, being the settings.json content. 

no bug here :)

**Comment by eamodio** [comment]
Phew! Thanks for digging into it!
