### ISSUE TITLE
not working with VSCode  1.13.1

### ISSUE THREAD

**Issue by NKjoep** [eamodio/vscode-toggle-excluded-files#4]
Hi!

I updated to the new Visual Studio Code version  1.13.1 and when I click the eye icon (or use the menu from the menu palette) it doesn't toggle the file visibility in the tree explorer.

I checked my settings and the excluded files properties don't change when using the extension.
With the previous version of VSC it worked.

Can you confirm this extension v1.6.0 works with VSC 1.13.1?

**Comment by eamodio** [comment]
@NKjoep It should work fine with 1.13.1 -- I haven't noticed any issues. If you toggle it more than once is there any difference? Did anything else change in your configuration?

**Comment by NKjoep** [comment]
Using the toggler more than once nothing happens, the configuration stays the same :/
is there a way to debug it somehow?

**Comment by NKjoep** [comment]
Ok I got the issue, was an old settings file I restored containing an old pattern to describe which files to exclude.

Look:

```js
  // this works
  "explorerExcludedFiles.patterns": [
    "file://.gitignore",
    "**/.git",
    "**/.DS_Store",
    "**/node_modules",
    "node_modules",
    "**/bower_components",
    "**/*.ngfactory.ts",
    "**/*.map",
    "**/*.scss.ts",
    "**/*.scss.shim.ts",
    "**/.git"
  ],

  // this don't
  "explorerExcludedFiles.patterns": [
    "file://.gitignore": true,
    "**/.git": true,
    "**/.DS_Store": true,
    "**/node_modules": true,
    "node_modules": true,
    "**/bower_components": true,
    "**/*.ngfactory.ts": true,
    "**/*.map": true,
    "**/*.scss.ts": true,
    "**/*.scss.shim.ts",
    "**/.git": true
]
```

So basically there was an error on the settings file, very difficult to spot it though.
