### ISSUE TITLE
Add Explorer Action Item menu entry to toggle visibility

### ISSUE THREAD

**Issue by kazenshi** [eamodio/vscode-toggle-excluded-files#44]
Similar to the `Scope to This` vscode extension, it would be nice to add an option to move the toggle icon to the Explorer Action Menu. This is their repo that supports it: https://github.com/rhalaly/scope-to-this-vscode

![Screenshot of the Scope to This extension doing this](https://user-images.githubusercontent.com/3218210/221331105-e4da1bf3-dba9-4565-815f-ac5ce2d4cd04.png)
_Screenshot of the Scope to This extension doing this_

**Comment by eamodio** [comment]
Added a new option (on by default) to support this.
