### ISSUE TITLE
Feature Request: Exclude from linting

### ISSUE THREAD

**Issue by bobrocke** [eamodio/vscode-toggle-excluded-files#5]
I am very pleased with this extension because it fills a real need, for me.

Are there APIs available that would allow this extension to exclude files in more contexts? In particular, I would like the excluded files to be excluded from code linters, too.

In my case, I have a folder full of third-party code excluded from the File Explore since I have no need to mess with that code. I would rather not see the linting errors found by VSC.

**Comment by eamodio** [comment]
This extension just toggles the `files.exclude` setting of vscode, it doesn't provide any exclusions itself. I would recommend opening an issue with vscode if you'd like that feature.
