### ISSUE TITLE
Feature Request: To distinguish workspace setting and user setting

### ISSUE THREAD

**Issue by zh-impact** [eamodio/vscode-toggle-excluded-files#7]
eg. One of situation was I want hidden some files all the time, like `.vscode` `package.json`. 
Another is hidden some file for work in progress, and modify for needed, like `.gitignore` and vary `.*rc` file

**Comment by charles-allen** [comment]
How would this work? You set your "hide all the time" in user settings?

I suspect extensions don't have access to the layers of settings; only the merged result of global + user + workspace.

Perhaps the solution is an extra extension specific setting: `alwaysExclude: []` which would be used to filter which are toggled. Though you'd probably need to have the extra same glob patterns!

**Comment by eamodio** [comment]
Sorry, but I'm not sure I understand the ask here.
